const fakeHotels = [
  {
    id: 1,
    hotelName: "Light bright airy stylish apt & safe peaceful stay",
    guests: 4,
    bedrooms: 2,
    bed: 2,
    cancellation: "Cancellation fexibility availiable",
    facilities: "Wif Air conditioning Kitchen",
    ratting: 4.9,
    photoUrl: "https://i.imgur.com/vzogJXj.png",
    price: 34,
  },
  {
    id: 2,
    hotelName: "Apartment in Lost Panorama",
    guests: 2,
    bedrooms: 1,
    bed: 1,
    cancellation: "Cancellation fexibility availiable",
    facilities: "Wif Air conditioning Kitchen",
    ratting: 5.0,
    photoUrl: "https://i.imgur.com/hI8yILw.png",
    price: 30,
  },
  {
    id: 3,
    hotelName: "AR Lounge & Pool (r&r + b&b)",
    guests: 4,
    bedrooms: 2,
    bed: 2,
    cancellation: "Cancellation fexibility availiable",
    facilities: "Wif Air conditioning Kitchen",
    ratting: 4.5,
    photoUrl: "https://i.imgur.com/Fi6XEJH.png",
    price: 38,
  },
];

export default fakeHotels;
