const fakeHotels = [
  {
    id: 1,
    placeId: 2,
    hotelName: "Light bright airy stylish apt & safe peaceful stay",
    guests: 4,
    bedrooms: 2,
    bed: 2,
    cancellation: "Cancellation fexibility availiable",
    facilities: "Wif Air conditioning Kitchen",
    ratting: 4.9,
    photoUrl: "https://i.imgur.com/vzogJXj.png",
    price: 34,
  },
  {
    id: 2,
    placeId: 2,
    hotelName: "Apartment in Lost Panorama",
    guests: 2,
    bedrooms: 1,
    bed: 1,
    cancellation: "Cancellation fexibility availiable",
    facilities: "Wif Air conditioning Kitchen",
    ratting: 5.0,
    photoUrl: "https://i.imgur.com/hI8yILw.png",
    price: 30,
  },
  {
    id: 3,
    placeId: 2,
    hotelName: "AR Lounge & Pool (r&r + b&b)",
    guests: 4,
    bedrooms: 2,
    bed: 2,
    cancellation: "Cancellation fexibility availiable",
    facilities: "Wif Air conditioning Kitchen",
    ratting: 4.5,
    photoUrl: "https://i.imgur.com/Fi6XEJH.png",
    price: 38,
  },
  {
    id: 4,
    placeId: 1,
    hotelName: "Prime Park Hotel)",
    guests: 4,
    bedrooms: 2,
    bed: 2,
    cancellation: "Cancellation fexibility availiable",
    facilities: "Wif Air conditioning Kitchen",
    ratting: 5.0,
    photoUrl: "https://i.imgur.com/7CGvYPM.jpg",
    price: 26,
  },
  {
    id: 5,
    placeId: 1,
    hotelName: "Long Beach Hotel",
    guests: 4,
    bedrooms: 2,
    bed: 2,
    cancellation: "Cancellation fexibility availiable",
    facilities: "Wif Air conditioning Kitchen",
    ratting: 5.0,
    photoUrl: "https://i.imgur.com/CmI2CKU.jpg",
    price: 20,
  },
  {
    id: 6,
    placeId: 1,
    hotelName: "Laguna Beach Hotel & Resort",
    guests: 4,
    bedrooms: 2,
    bed: 2,
    cancellation: "Cancellation fexibility availiable",
    facilities: "Wif Air conditioning Kitchen",
    ratting: 4.9,
    photoUrl: "https://i.imgur.com/xw4Bkxb.jpg",
    price: 27,
  },
  {
    id: 7,
    placeId: 4,
    hotelName: "Resort RungRang - Sajek",
    guests: 4,
    bedrooms: 2,
    bed: 2,
    cancellation: "Cancellation fexibility availiable",
    facilities: "Wif Air conditioning Kitchen",
    ratting: 4.6,
    photoUrl: "https://i.imgur.com/1GXRiJ2.jpg",
    price: 22,
  },
  {
    id: 8,
    placeId: 4,
    hotelName: "Keeper’s Inn",
    guests: 4,
    bedrooms: 2,
    bed: 2,
    cancellation: "Cancellation fexibility availiable",
    facilities: "Wif Air conditioning Kitchen",
    ratting: 4.5,
    photoUrl: "https://i.imgur.com/nmnakQm.jpg",
    price: 22,
  },
  {
    id: 9,
    placeId: 4,
    hotelName: "Monu Adom Resort",
    guests: 4,
    bedrooms: 2,
    bed: 2,
    cancellation: "Cancellation fexibility availiable",
    facilities: "Wif Air conditioning Kitchen",
    ratting: 4.5,
    photoUrl: "https://i.imgur.com/Dd9bTDK.jpg",
    price: 22,
  },
  {
    id: 10,
    placeId: 3,
    hotelName: "Sundarban Tiger Roar Resort",
    guests: 4,
    bedrooms: 2,
    bed: 2,
    cancellation: "Cancellation fexibility availiable",
    facilities: "Wif Air conditioning Kitchen",
    ratting: 4.5,
    photoUrl: "https://i.imgur.com/sT60EiW.jpg",
    price: 22,
  },
  {
    id: 11,
    placeId: 6,
    hotelName: "Bono Nibash Hill Resort",
    guests: 4,
    bedrooms: 2,
    bed: 2,
    cancellation: "Cancellation fexibility availiable",
    facilities: "Wif Air conditioning Kitchen",
    ratting: 4.5,
    photoUrl: "https://i.imgur.com/n0AslVo.jpg",
    price: 22,
  },
  {
    id: 12,
    placeId: 6,
    hotelName: "Fanush Resort",
    guests: 4,
    bedrooms: 2,
    bed: 2,
    cancellation: "Cancellation fexibility availiable",
    facilities: "Wif Air conditioning Kitchen",
    ratting: 4.5,
    photoUrl: "https://i.imgur.com/zC70N6a.jpg",
    price: 22,
  },
];

export default fakeHotels;
